version: "3.9"
services:
  realsense_ros2:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - /dev:/dev
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'
