version: "3"
services:
  realsense_ros2:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'
    environment:
      - DISPLAY=unix${DISPLAY}
      - QT_X11_NO_MITSHM=1
